### ISSUE TITLE
Tile_planner.py Attribute error 

### ISSUE THREAD

**Issue by AymenFJA** [iceberg-project/ASIFT#30]
Hello @mmacferrin ,

I was trying to run the `tile_planner.py` from `phase1` and I am getting the following error :
```
         File "tile_planner.py", line 388, in <module>
         verbose = args.verbose)
         File "tile_planner.py", line 48, in create_tiles_from_image
         scratch_basename = m.lookup(img_filename)
         File 
         "ASIFT/src/phase_1_image_preprocessing/scratch_directory_manager.py", line 71, in lookup
         self.read_logfile()
         File "ASIFT/src/phase_1_image_preprocessing/scratch_directory_manager.py", line 65, in 
         read_logfile
         self.logfile_numpy_dt = self.logfile_data.dtype
AttributeError: 'NoneType' object has no attribute 'dtype
```
any ideas on why i am getting this ? thanks .

**Comment by mmacferrin** [comment]
Aymen, did you set up the Scratch directory first?

In the ASIFT/src/README.md, you need to create a directory where your Scratch files will sit and place a copy of the "scratch_directory_log.csv" file in there for the Manager to work. The scratch_directory_manager.py is expecting a scratch folder to be in place and for the csv file to be there when you start processing.

I had a scratch folder in the code already, but Ioannis indicated strongly we should nix that, so I got rid of it and put those instructions in the README.md. I understand the desire to not have a file scratch directory in the same location as the source code, that makes sense, but at present implementation, on whatever machine this is running, a Scratch directory should be set and its location noted in file_locations.py before the code is run.

That bit of code works, just the scratch directory wasn't set up yet, so it couldn't read the logfile because it didn't exist there.

I'll update the code so that it sets that directory up automatically on first run, in the location specified in "src/file_locations.py". That will make it a bit easier to run "out of the box", one less set of setup instructions to follow. If you don't want the directory created in "ASIFT/src/asift_scratch", you can chnage that in file_locations.py before running. Change the line for "ASIFT_Scratch_Dir" on line 20 of file_locations.py accordingly.

**Comment by mmacferrin** [comment]
Edited: I got a bit of code updated so you don't have to set up the directory manually, the code will do it for you on first run (hard to say if the directory is exactly where you want it but you can change file_locations.py accordingly before running).

I'm having an error on the commit/push and I *really* need to go get my daughter, but I'll update it later tonight once I resolve the push error.

**Comment by mmacferrin** [comment]
Commit done. Code can be tested on your end.

To explain, this wasn't a bug or an attribute error, it arose from a lack of reading the "README" instructions. The README explained what needed to be done, it takes 10-30 seconds.

With the commit, if the Scratch directory & logfile don't exist when the code is first run, it will (by default, using an optional parameter) create them upon the first run of the code, in the locations specified in "file_locations.py". The code won't break but it may put the files where you don't want them in an "asift_scratch" folder alongside the code, given that the code has no obvious prior knowledge of your file system. If you prefer the Scratch folders/files to be in a different place, specify those locations in "file_locations.py".

Hope it helps.

**Comment by AymenFJA** [comment]
Mike ,

When I tested your code, I did set up the scratch folder, I think when you removed the scratch folder based on Giannis request you did not fix the dependencies related to the scratch folder in your code, so it’s actually a bug, but thanks anyway for fixing it.

**Comment by mmacferrin** [comment]
Aymen, given your statement, it's unclear if you understand what happened. I'll explain it one last time to avoid you running into this again in the future. It'd save you time next time.

If the scratch folder were set up as specified in the README, then that particular error you posted doesn't happen. SCRATCH_Manager::lookup() only returns "None" if the logfile and/or folder didn't exist at the location specified. Nothing else would have caused that particular error. I didn't neglect to "fix the dependencies related to the scratch folder" in the code. The code was already modified to comply with Giannis' request. If a stated README dependency isn't met before the code is run, that isn't a bug, it's just user error.

I updated the code to raise a clear Warning if it happens again, hopefully it won't stump the next person who uses it if they didn't set up the folder. (With the new default behavior it shouldn't usually need the Warning, but the redundancy doesn't hurt, to make an error clearer if it happens again.)

Simple mistakes happen, I get it. I could've easily done that myself, especially with someone else's code. I just wanted to make sure you understand what happened so you don't run into this particular issue again. If you say it's fixed now, then the ticket is resolved, I'll go ahead and close it.

**Comment by AymenFJA** [comment]
Hello @mmacferrin  , thanks for the explanation again! I think you are missing the point that I was trying to make but that is ok. Anyway, I will test the code again and if everything is working I would be happy to close this and move forward so we can merge your branch with the devel, again thanks for fixing the code. 

`The issue will be reopened now !  and will be closed after testing and running the code.`

**Comment by iparask** [comment]
Hello @mmacferrin, @AymenFJA  and I are testing with Aymen `tile_planner.py` and we are still getting an error. Our environment is:
```bash
[paraskev@r001 phase_1_image_preprocessing]$ module list
Currently Loaded Modulefiles:
  1) psc_path/1.1                3) intel/19.3                  5) python2/2.7.11_gcc          7) python2/2.7.11_gcc_np1.11
  2) slurm/default               4) xdusage/2.1-1               6) gcc/5.3.0                   8) opencv/2.4.13.2
[paraskev@r001 phase_1_image_preprocessing]$
```
We got:
```bash
[paraskev@r001 phase_1_image_preprocessing]$ python tile_planner.py /pylon5/mc3bggp/bspitz/WV03_20170217064537_10400100297FEA00_17FEB17064537-M1BS-057107305010_01_P001_u08rf3031.tif -tilesize 3000 -csv_file test.csv -nodata 0 --verbose
Traceback (most recent call last):
  File "tile_planner.py", line 388, in <module>
    verbose = args.verbose)
  File "tile_planner.py", line 48, in create_tiles_from_image
    scratch_basename = m.lookup(img_filename)
  File "/pylon5/mc3bggp/paraskev/ASIFT/src/phase_1_image_preprocessing/scratch_directory_manager.py", line 83, in lookup
    self.read_logfile()
  File "/pylon5/mc3bggp/paraskev/ASIFT/src/phase_1_image_preprocessing/scratch_directory_manager.py", line 67, in read_logfile
    if not os.path.exists(self.logfile, verbose=True):
TypeError: exists() got an unexpected keyword argument 'verbose'
```

The image you see there is a World View image under @bspitzbart  account that I used for the Seals use case. Are we missing something?

**Comment by mmacferrin** [comment]
My bad on that update. Remove "verbose=True" from that line and that's fixed.

Due to the re-scoping of the project moving forward, this will be among the last of these interactions on this particular workflow for a little while here.

**Comment by AymenFJA** [comment]
Closed for now.

**Comment by AymenFJA** [comment]
`verbose=true` is removed, this ticket is officially closed.
